@startuml Arduino Context Diagram

actor "User" as user
Rectangle "Server" as server
Rectangle "Arduino" as sensor
usecase "Sensor System" as system

user-->system
system -->server
sensor-->system
system-->sensor

@enduml