@startuml Class Diagram
left to right direction

abstract class Vehicle{
	-int speed
	+void move()
}

SpeedInterface <|.- Vehicle
interface SpeedInterface{
	+int getSpeed()
	+void speedUp()
	+void slowDown()
}

Vehicle <|- Train
abstract class Train{
	-int fuelPercentage
	+void speedUp()
	+void slowDown()
	+void fillFuel()
}

FuelInterface <|.- Train
interface FuelInterface{
	+int getFuelPercentage()
	+void fillFuel()
}

Train <|- ElectricTrain
class ElectricTrain{
	+void fillFuel()
}

Train <|- DieselTrain
class DieselTrain{
	+void fillFuel()
}

@enduml